// Base Map setup
const rasterLayer = new ol.layer.Tile({
    source: new ol.source.OSM() // Using OpenStreetMap as default for MVP since it's easy and doesn't require API keys
});

const vectorSource = new ol.source.Vector({ wrapX: false });
const vectorLayer = new ol.layer.Vector({
    source: vectorSource,
    style: new ol.style.Style({
        fill: new ol.style.Fill({
            color: 'rgba(0, 153, 255, 0.2)',
        }),
        stroke: new ol.style.Stroke({
            color: '#0099ff',
            width: 2,
        }),
    }),
});

// Layer for showing Semantic Segmentation
const changesSource = new ol.source.Vector();
const changesLayer = new ol.layer.Vector({
    source: changesSource,
    style: function(feature) {
        let color = 'rgba(255, 0, 0, 0.5)'; // Red for Optical
        let stroke = 'red';
        
        // Color SAR geometry yellow and Optical red based on current pipeline
        if (window.currentUsedSensor === 'sar') {
            color = 'rgba(255, 255, 0, 0.5)'; // Yellow for SAR
            stroke = '#b8860b'; // Dark Goldenrod for outline
        }
        
        return new ol.style.Style({
            fill: new ol.style.Fill({ color: color }),
            stroke: new ol.style.Stroke({ color: stroke, width: 3 })
        });
    }
});

const map = new ol.Map({
    target: 'map',
    layers: [rasterLayer, vectorLayer, changesLayer],
    view: new ol.View({
        center: ol.proj.fromLonLat([85.8245, 20.2961]), // Center of Bhubaneswar
        zoom: 12
    })
});

let drawInteractive;
let drawnGeoJSON = null;
const apiBaseUrl = 'http://localhost:8000'; // Make sure backend runs here

document.getElementById('draw-btn').addEventListener('click', () => {
    map.removeInteraction(drawInteractive);
    drawInteractive = new ol.interaction.Draw({
        source: vectorSource,
        type: 'Polygon',
    });

    drawInteractive.on('drawend', (event) => {
        const feature = event.feature;
        const geometry = feature.getGeometry();
        // Convert to EPSG:4326 for standard GeoJSON format
        const geom4326 = geometry.clone().transform('EPSG:3857', 'EPSG:4326');
        const format = new ol.format.GeoJSON();
        drawnGeoJSON = format.writeGeometryObject(geom4326);

        document.getElementById('analyze-btn').disabled = false;
        map.removeInteraction(drawInteractive);
    });

    map.addInteraction(drawInteractive);
});

// Select Interaction dynamically lets users click the anomalies generated by mathematical models!
const selectInteractive = new ol.interaction.Select({
    layers: [changesLayer]
});
map.addInteraction(selectInteractive);

let selectedAnomalyGeom = null;

selectInteractive.on('select', function(e) {
    const selectedFeatures = e.target.getFeatures();
    const inspector = document.getElementById('anomaly-inspector');
    
    if (selectedFeatures.getLength() > 0) {
        const feature = selectedFeatures.item(0);
        document.getElementById('vlm-response').innerText = "";
        
        // Save the raw mathematical geometry so we can feed this explicit crop to the VLM
        selectedAnomalyGeom = feature.getGeometry().clone().transform('EPSG:3857', 'EPSG:4326');
        inspector.classList.remove('d-none');
    } else {
        inspector.classList.add('d-none');
        selectedAnomalyGeom = null;
    }
});

document.getElementById('vlm-btn').addEventListener('click', async () => {
    if (!selectedAnomalyGeom) return;
    
    const query = document.getElementById('vlm-input').value;
    const format = new ol.format.GeoJSON();
    const geomJson = format.writeGeometryObject(selectedAnomalyGeom);
    
    document.getElementById('vlm-btn').innerText = "Processing Contextual Pixels...";
    document.getElementById('vlm-btn').disabled = true;
    
    try {
        const response = await fetch(`${apiBaseUrl}/api/vqa`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ query: query, geometry: JSON.parse(geomJson) })
        });
        const data = await response.json();
        document.getElementById('vlm-response').innerText = "Insight Generated: " + data.answer;
    } catch (e) {
        document.getElementById('vlm-response').innerText = "VLM Connection Error: " + e;
    } finally {
        document.getElementById('vlm-btn').innerText = "Submit Query to GalaxEye VLM";
        document.getElementById('vlm-btn').disabled = false;
    }
});

document.getElementById('clear-btn').addEventListener('click', () => {
    vectorSource.clear();
    changesSource.clear();
    drawnGeoJSON = null;
    document.getElementById('analyze-btn').disabled = true;
    document.getElementById('alert-box').style.display = 'none';
    map.removeInteraction(drawInteractive);
});

document.getElementById('analyze-btn').addEventListener('click', async () => {
    const aoiName = document.getElementById('aoi-name').value || "Unnamed AOI";
    const spinner = document.getElementById('status-spinner');
    const alertBox = document.getElementById('alert-box');
    const alertMessage = document.getElementById('alert-message');

    if (!drawnGeoJSON) return;

    spinner.classList.remove('d-none');
    document.getElementById('analyze-btn').disabled = true;
    alertBox.style.display = 'none';
    changesSource.clear();

    try {
        // Step 1: Save AOI
        const aoiResponse = await fetch(`${apiBaseUrl}/api/aoi`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: aoiName, geojson: { type: 'Feature', geometry: drawnGeoJSON } })
        });

        let aoiData = await aoiResponse.json();

        if (aoiResponse.ok) {
            const aoiId = aoiData.aoi_id;

            // Step 2: Trigger Analysis with GalaxEye attributes
            const sensorVal = document.getElementById('sensor-type').value;
            window.currentUsedSensor = sensorVal; // Attach globally for OpenLayers styler

            const reqBody = {
                sensor: sensorVal,
                start_date: document.getElementById('start-date').value,
                end_date: document.getElementById('end-date').value
            };

            const analyzeResponse = await fetch(`${apiBaseUrl}/api/analyze/${aoiId}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(reqBody)
            });
            const analyzeData = await analyzeResponse.json();

            if (analyzeResponse.ok) {
                // Display changes
                const format = new ol.format.GeoJSON();
                const features = format.readFeatures(analyzeData.changes, {
                    featureProjection: 'EPSG:3857'
                });
                changesSource.addFeatures(features);

                // Show Alert
                alertBox.style.display = 'block';
                alertMessage.innerText = analyzeData.message || "Analysis complete.";
            } else {
                alert("Analysis failed: " + JSON.stringify(analyzeData));
            }
        } else {
            alert("Failed to save AOI: " + JSON.stringify(aoiData));
        }

    } catch (e) {
        console.error(e);
        alert("Server error. Is the backend running?");
    } finally {
        spinner.classList.add('d-none');
        document.getElementById('analyze-btn').disabled = false;
    }
});
